//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\antlr\Cool.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419




#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS3021 // Type or member does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
#pragma warning disable CS0105 //The using directive for 'System.Collections.Generic' appeared previously in this namespace [D:\Desktop\projects\coolc\coolc\src\coolc\coolc.csproj


using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CoolParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ICoolListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CoolParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CoolParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CoolParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CoolParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CoolParser.classdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassdef([NotNull] CoolParser.ClassdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CoolParser.classdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassdef([NotNull] CoolParser.ClassdefContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>methodFeature</c>
	/// labeled alternative in <see cref="CoolParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodFeature([NotNull] CoolParser.MethodFeatureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>methodFeature</c>
	/// labeled alternative in <see cref="CoolParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodFeature([NotNull] CoolParser.MethodFeatureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>attribFeature</c>
	/// labeled alternative in <see cref="CoolParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribFeature([NotNull] CoolParser.AttribFeatureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>attribFeature</c>
	/// labeled alternative in <see cref="CoolParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribFeature([NotNull] CoolParser.AttribFeatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CoolParser.formal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal([NotNull] CoolParser.FormalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CoolParser.formal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal([NotNull] CoolParser.FormalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lessExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessExp([NotNull] CoolParser.LessExpContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>lessExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterBiggerExp([NotNull] CoolParser.BiggerExpContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>lessExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitLessExp([NotNull] CoolParser.LessExpContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>identifierExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitBiggerExp([NotNull] CoolParser.BiggerExpContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>identifierExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param> 
    void EnterIdentifierExp([NotNull] CoolParser.IdentifierExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExp([NotNull] CoolParser.IdentifierExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>assignExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignExp([NotNull] CoolParser.AssignExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>assignExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignExp([NotNull] CoolParser.AssignExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atsimExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtsimExp([NotNull] CoolParser.AtsimExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atsimExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtsimExp([NotNull] CoolParser.AtsimExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>isvoidExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsvoidExp([NotNull] CoolParser.IsvoidExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>isvoidExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsvoidExp([NotNull] CoolParser.IsvoidExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExp([NotNull] CoolParser.BoolExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExp([NotNull] CoolParser.BoolExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lessEqualExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessEqualExp([NotNull] CoolParser.LessEqualExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lessEqualExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLessEqualExp([NotNull] CoolParser.LessEqualExpContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>whileExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterBiggerEqualExp([NotNull] CoolParser.BiggerEqualExpContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>lessEqualExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitBiggerEqualExp([NotNull] CoolParser.BiggerEqualExpContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>whileExp</c>
    /// labeled alternative in <see cref="CoolParser.expresion"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param> 

    void EnterWhileExp([NotNull] CoolParser.WhileExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>whileExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileExp([NotNull] CoolParser.WhileExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExp([NotNull] CoolParser.NotExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExp([NotNull] CoolParser.NotExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bracedExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracedExp([NotNull] CoolParser.BracedExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bracedExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracedExp([NotNull] CoolParser.BracedExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>letExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetExp([NotNull] CoolParser.LetExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>letExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetExp([NotNull] CoolParser.LetExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parentExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParentExp([NotNull] CoolParser.ParentExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parentExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParentExp([NotNull] CoolParser.ParentExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>equalsExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualsExp([NotNull] CoolParser.EqualsExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>equalsExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualsExp([NotNull] CoolParser.EqualsExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExp([NotNull] CoolParser.IfExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExp([NotNull] CoolParser.IfExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tildeExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTildeExp([NotNull] CoolParser.TildeExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tildeExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTildeExp([NotNull] CoolParser.TildeExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>methodCallExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallExp([NotNull] CoolParser.MethodCallExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>methodCallExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallExp([NotNull] CoolParser.MethodCallExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>newTypeExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewTypeExp([NotNull] CoolParser.NewTypeExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>newTypeExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewTypeExp([NotNull] CoolParser.NewTypeExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stringExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringExp([NotNull] CoolParser.StringExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stringExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringExp([NotNull] CoolParser.StringExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>infixExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfixExp([NotNull] CoolParser.InfixExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>infixExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfixExp([NotNull] CoolParser.InfixExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>intExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntExp([NotNull] CoolParser.IntExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>intExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntExp([NotNull] CoolParser.IntExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseExp([NotNull] CoolParser.CaseExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseExp</c>
	/// labeled alternative in <see cref="CoolParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseExp([NotNull] CoolParser.CaseExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CoolParser.newvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewvar([NotNull] CoolParser.NewvarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CoolParser.newvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewvar([NotNull] CoolParser.NewvarContext context);
}
